server:
  port: 9092
  error:
    include-stacktrace: never

spring:
  thymeleaf:
    cache: false
  security:
    user:
      password: secret

logging:
  level:
    root: info
    org:
      springframework:
        web: info

library:
  server: http://localhost:9091/library-server
